
################################################################################
# CODE MODE: Vicuna_Condi_Token_MBPS_TopK#######################################
################################################################################
defaults:
 - base_koala
 - _self_

 # Single Prompt Model
prompt_length: 5
# max_decoding_length: 10
# prompt_train_batch_size: 16
# prompt_train_batch_size: 8
# prompt_infer_batch_size: 1
# SQL Module
reward_shaping_old_min: 0
reward_shaping_old_max: 1
reward_shaping_new_min: 0
reward_shaping_new_max: 5
top_k: 256
# Trainer
max_train_steps: 80000
train_shuffle: false
eval_steps: 100
# eval_steps: 10
# eval_steps: 2
save_steps: 100
learning_rate: 5e-5
random_seed: null

source_train_reps: 20
source_infer_reps: 1
train_batch_size: 3
eval_batch_size: 3

# fluent: false
fluent: True

########################################
report_to_wandb: false #2/2           ##
# report_to_wandb: true                 ##
                                      ##
########################################

# is_mask_lm: false
# compute_zscore: true
# incorrect_coeff: 180.0
# correct_coeff: 200.0

# policy_lm: distilgpt2 ##############################

# hidden_size: 2048
# logit_bias: 0.0
# fluent: true
# fluent_top_k: 20
# max_decoding_length: 5
# eos_token_id: null
# prompt_length: 5
# prompt_train_batch_size: 16
# prompt_infer_batch_size: 1
# source_str: <|endoftext|>
# sql_loss_impl: v2_v2r_v3_v3r
# training_mode: sql-onpolicy
# mix_strategy: null
# target_update_method: polyak
# target_update_steps: null
# target_learning_rate: 0.001
# reward_shaping: true
# reward_shaping_old_min: 0.0
# reward_shaping_old_max: 1.0
# reward_shaping_new_min: 0.0
# reward_shaping_new_max: 5.0
# top_k: 256
# top_p: 1.0
# num_beams: 1
# 
# train_shuffle: false
# train_drop_last: true
# num_train_epochs: 1
# max_train_steps: 12000
# do_eval: true
# eval_batch_size: 16
# eval_steps: 10
# do_save: true
# save_dir: ./outputs
# save_steps: 100
# learning_rate: 5.0e-05
# gradient_clip: true
# gradient_clip_norm: 5.0
# checkpoint_path: null
# checkpoint_path: /raid/zhichao/qufeiyu/nlp/vi/debias_koala_rlprompt/outputs/2023-06-07/23-34-24/outputs/ckpt/ckpt.step.40000.pth #<prompt>+<sentence>: kl003
# checkpoint_path: /raid/zhichao/qufeiyu/nlp/vi/debias_koala_rlprompt/outputs/2023-06-07/23-27-34/outputs/ckpt/ckpt.step.40000.pth #<prompt>+<sentence>: res02
# checkpoint_path: /raid/zhichao/qufeiyu/nlp/vi/debias_koala_rlprompt/outputs/2023-06-07/23-17-26/outputs/ckpt/ckpt.step.40000.pth #<prompt>+<sentence>: rlprompt
# checkpoint_path: /raid/zhichao/qufeiyu/nlp/vi/debias_koala_rlprompt/outputs/2023-06-07/23-17-14/outputs/ckpt/ckpt.step.40000.pth #<prompt>+<sentence>: 10_div
# random_seed: null
# report_to_wandb: false
# project_name: rl-prompt
# run_name: null

checkpoint_path: null  # Train

# Condi/___Vicuna_Condi_Token_MBPS_NoFluentTech:
# checkpoint_path: /raid/zhichao/qufeiyu/nlp/vi/debias_koala_rlprompt/outputs/2023-06-10/20-20-18/outputs/ckpt/ckpt.step.40000.pth
# Condi/___Vicuna_Condi_Sentence_MBPS_NoFluentTech
# checkpoint_path: /raid/zhichao/qufeiyu/nlp/vi/debias_koala_rlprompt/outputs/2023-06-10/20-32-37/outputs/ckpt/ckpt.step.40000.pth
# ___Vicuna_Condi_Token_MBPS_TopK
# checkpoint_path: /raid/zhichao/qufeiyu/nlp/vi/debias_koala_rlprompt/outputs/2023-06-10/20-31-33/outputs/ckpt/ckpt.step.40000.pth
# ___Vicuna_Condi_Sentence_MBPS_TopK
# checkpoint_path: /raid/zhichao/qufeiyu/nlp/vi/debias_koala_rlprompt/outputs/2023-06-10/20-24-13/outputs/ckpt/ckpt.step.40000.pth

# ___40000_distillgpt2_CondVicuna_20Pcandi_Res02_div10_
# checkpoint_path: /raid/zhichao/qufeiyu/nlp/vi/debias_koala_rlprompt/outputs/2023-06-07/23-27-34/outputs/ckpt/ckpt.step.40000.pth
# ___40000_distillgpt2_CondVicuna_20Pcandi_kl003_div10_
# checkpoint_path: /raid/zhichao/qufeiyu/nlp/vi/debias_koala_rlprompt/outputs/2023-06-07/23-33-11/outputs/ckpt/ckpt.step.40000.pth
# ___40000_distillgpt2_CondVicuna_20Pcandi_kl0003_div10_
# checkpoint_path: /raid/zhichao/qufeiyu/nlp/vi/debias_koala_rlprompt/outputs/2023-06-07/23-33-37/outputs/ckpt/ckpt.step.40000.pth
# ___40000_distillgpt2_CondVicuna_20Pcandi_kl003__
# checkpoint_path: /raid/zhichao/qufeiyu/nlp/vi/debias_koala_rlprompt/outputs/2023-06-07/23-34-24/outputs/ckpt/ckpt.step.40000.pth
# ___40000_distillgpt2_CondVicuna_20Pcandi_Res02_
# checkpoint_path: /raid/zhichao/qufeiyu/nlp/vi/debias_koala_rlprompt/outputs/2023-06-07/23-26-24/outputs/ckpt/ckpt.step.40000.pth


# ----2024 Eval
# checkpoint_path: /share/home/wenqingchen/feiyu/RL_debias/outputs/2024-03-24/15-46-39/outputs/ckpt/ckpt.step.27500.pth
# checkpoint_path: /share/home/wenqingchen/feiyu/RL_debias/outputs/2024-03-26/15-24-56/outputs/ckpt/ckpt.step.26000.pth #alpha = 0, 26000 epoch
# checkpoint_path: /share/home/wenqingchen/feiyu/RL_debias/outputs/2024-03-26/15-47-12/outputs/ckpt/ckpt.step.26000.pth #alpha = 0.2, 26000 epoch
# checkpoint_path: /share/home/wenqingchen/feiyu/RL_debias/outputs/2024-03-26/15-47-31/outputs/ckpt/ckpt.step.26000.pth #alpha = 0.4, 26000 epoch
# checkpoint_path: /share/home/wenqingchen/feiyu/RL_debias/outputs/2024-03-26/15-47-36/outputs/ckpt/ckpt.step.26000.pth #alpha = 0.6, 26000 epoch
# checkpoint_path: /share/home/wenqingchen/feiyu/RL_debias/outputs/2024-03-26/15-47-50/outputs/ckpt/ckpt.step.26000.pth #alpha = 0.8, 26000 epoch
# checkpoint_path: /share/home/wenqingchen/feiyu/RL_debias/outputs/2024-03-26/15-48-04/outputs/ckpt/ckpt.step.26000.pth #alpha = 1.0, 26000 epoch
# checkpoint_path: 


